# 10001 - waving plants (only top of the model moves)
block.10001=short_grass tall_grass fern large_fern dandelion poppy blue_orchid allium azure_bluet red_tulip orange_tulip white_tulip pink_tulip oxeye_daisy cornflower lily_of_the_valley sunflower lilac rose_bush peony wheat carrots potatoes beetroots sweet_berry_bush torchflower pitcher_plant pink_petals wildflowers leaf_litter bush firefly_bush
# 10002 - waving leaves
block.10002=oak_leaves spruce_leaves birch_leaves jungle_leaves acacia_leaves dark_oak_leaves mangrove_leaves cherry_leaves azalea_leaves flowering_azalea_leaves pale_oak_leaves
# 10010 - water (waves + reflections)
block.10010=water
